#!/bin/bash
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

# Activate VirtualEnv in order to use the correct libraries
source ${VIRTUAL_ENV}/bin/activate

if [ ! -d $OPENSHIFT_REPO_DIR/wsgi/static ]; then
mkdir $OPENSHIFT_REPO_DIR/wsgi/static
fi

if [ ! -d $OPENSHIFT_REPO_DIR/wsgi/static/.htaccess ]; then
touch $OPENSHIFT_REPO_DIR/wsgi/static/.htaccess
fi

echo "RewriteEngine On" > $OPENSHIFT_REPO_DIR/wsgi/static/.htaccess
echo "RewriteRule ^application/static/(.+)$ /static/$1 [L]" >> $OPENSHIFT_REPO_DIR/wsgi/static/.htaccess:

if [ ! -d $OPENSHIFT_DATA_DIR/media ]; then
mkdir $OPENSHIFT_DATA_DIR/media
fi

ln -sf $OPENSHIFT_DATA_DIR/media $OPENSHIFT_REPO_DIR/wsgi/static/media
