---
- hosts: www.hearcloud.com
  remote_user: mpvillafranca
  become: yes
  tasks:
  - name: Include vars
    include_vars: vars.yml

  - name: Update package repositories
    when: ansible_os_family == 'Debian'
    become_method: sudo
    apt: update_cache=yes

  - name: Install python, pip, libjpeg, git, supervisor, nginx and ssl
    when: ansible_os_family == 'Debian'
    apt: package={{ item }} state=installed
    with_items:
      - python-setuptools
      - build-essential
      - python-dev
      - python-pip 
      - python-dev
      - python-mysqldb
      - libjpeg-dev
      - zlib1g-dev
      - nginx
      - supervisor
      - git
      - build-essential
      - libssl1.0.0
      - libssl-dev
      - libffi-dev  

  - name: Install ffmpeg dependencies
    when: ansible_os_family == 'Debian'
    apt: package={{ item }} state=installed
    with_items:
      - checkinstall 
      - libfaac-dev
      - libgpac-dev
      - libjack-jackd2-dev
      - libmp3lame-dev 
      - libopencore-amrnb-dev 
      - libopencore-amrwb-dev
      - librtmp-dev 
      - libsdl1.2-dev 
      - libtheora-dev 
      - libva-dev 
      - libvdpau-dev 
      - libvorbis-dev
      - libx11-dev
      - libxfixes-dev
      - pkg-config
      - texi2html
      - yasm
      - zlib1g-dev

  - name: Set MySQL root password before installing
    debconf: name='mysql-server' question='mysql-server/root_password' value='{{dbpassword | quote}}' vtype='password'

  - name: Confirm MySQL root password before installing
    debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{dbpassword | quote}}' vtype='password'

  - name: Install MySQL
    apt: package={{ item }} state=installed force=yes update_cache=yes cache_valid_time=3600
    when: ansible_os_family == 'Debian'
    with_items:
      - mysql-server
      - libmysqlclient-dev


  - name: Start the MySQL service
    action: service name=mysql state=started

  - name: Modify configuration file to listen on all interfaces
    lineinfile: dest=/etc/mysql/my.cnf regexp="^bind-address" line="bind-address=0.0.0.0"

  - name: Restart MySQL
    service: name=mysql state=restarted

  - name: Create database
    mysql_db: name={{dbname}} login_password={{dbpassword | quote}} state=present

  - name: Pip upgrade
    pip: name=pip extra_args='--upgrade'

  - name: Install virtualenv via pip
    pip: name=virtualenv state=present

  - name: Virtual environment creation
    become_user: mpvillafranca
    command: virtualenv /home/{{username}}/VirtualEnvs/hcenv -p python2.7 creates="/home/{{username}}/VirtualEnvs/hcenv"

  - name: Clone repository
    become_user: mpvillafranca
    git: repo=https://github.com/hearcloud/hearcloud.git  dest=/home/{{username}}/hearcloud clone=yes force=yes version=dev
    
  - name: Install project requirements via pip
    become_user: mpvillafranca
    pip: requirements=/home/{{username}}/hearcloud/requirements/production.txt virtualenv=/home/{{username}}/VirtualEnvs/hcenv state=present

  - name: Add permissions over /var/www to the group varwwwusers and set to 770
    file: path=/var/www/ group=www-data mode=770 recurse=yes
