---
- hosts: www.hearcloud.com
  vars:
    username: mpvillafranca
  remote_user: mpvillafranca
  become: yes
  tasks:
  - name: Update package repositories
    when: ansible_os_family == 'Debian'
    become_method: sudo
    apt: update_cache=yes

  - name: Install python, pip, libjpeg, git, supervisor and nginx
    when: ansible_os_family == 'Debian'
    become_method: sudo
    apt: package={{ item }} state=installed
    with_items:
      - python-setuptools
      - build-essential
      - python-dev
      - python-pip 
      - python-dev
      - python-mysqldb
      - libjpeg-dev
      - zlib1g-dev
      - nginx
      - supervisor
      - git
      - build-essential

  - name: Install ffmpeg dependencies
    when: ansible_os_family == 'Debian'
    become_method: sudo
    apt: package={{ item }} state=installed
    with_items:
      - checkinstall 
      - libfaac-dev
      - libgpac-dev
      - libjack-jackd2-dev
      - libmp3lame-dev 
      - libopencore-amrnb-dev 
      - libopencore-amrwb-dev
      - librtmp-dev 
      - libsdl1.2-dev 
      - libtheora-dev 
      - libva-dev 
      - libvdpau-dev 
      - libvorbis-dev
      - libx11-dev
      - libxfixes-dev
      - pkg-config
      - texi2html
      - yasm
      - zlib1g-dev

  - name: Set MySQL root password before installing
    become_method: sudo
    debconf: name='mysql-server' question='mysql-server/root_password' value='{{lookup('env', 'MYSQL_PASS') | quote}}' vtype='password'

  - name: Confirm MySQL root password before installing
    become_method: sudo
    debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{lookup('env', 'MYSQL_PASS') | quote}}' vtype='password'

  - name: Install MySQL
    become_method: sudo
    apt: package={{ item }} state=installed force=yes update_cache=yes cache_valid_time=3600
    when: ansible_os_family == 'Debian'
    with_items:
      - mysql-server
      - libmysqlclient-dev

  - name: Start the MySQL service
    action: service name=mysql state=started

  - name: Create database
    mysql_db: name={{lookup('env', 'MYSQL_DB')}} login_password={{lookup('env', 'MYSQL_PASS') | quote}} state=present

  - name: Pip upgrade
    become_method: sudo
    pip: name=pip extra_args='--upgrade'

  - name: Install virtualenv via pip
    become_method: sudo
    pip: name=virtualenv state=present

  - name: Virtual environment creation
    command: virtualenv /home/{{username}}/VirtualEnvs/hcenv -p python2.7 creates="/home/{{username}}/VirtualEnvs/hcenv"

  - name: Clone repository
    git: repo=https://github.com/hearcloud/hearcloud.git  dest=/home/{{username}}/hearcloud clone=yes force=yes
    
  - name: Install project requirements via pip
    pip: requirements=/home/{{username}}/hearcloud/requirements/production.txt virtualenv=/home/{{username}}/VirtualEnvs/hcenv state=present
