# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-17 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0002_song_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='original_filename',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Original filename'),
        ),
    ]
