# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-17 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0004_auto_20160818_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='playlists',
            field=models.ManyToManyField(to='box.Playlist'),
        ),
    ]
