# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 07:31
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('ctime', models.DateField(auto_now_add=True)),
                ('mtime', models.DateField(auto_now=True)),
                ('slug', models.SlugField()),
                ('audio_file', models.FileField(default='', upload_to=b'')),
                ('mime_type', models.CharField(blank=True, max_length=256, verbose_name='Mime type')),
                ('artwork', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('song_title', models.CharField(blank=True, max_length=250, null=True)),
                ('artist', models.CharField(blank=True, max_length=250, null=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(3000)])),
                ('album', models.CharField(blank=True, max_length=500, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('album_artist', models.CharField(blank=True, max_length=250, null=True)),
                ('track_number', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(3000)])),
                ('bpm', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(300)])),
                ('original_artist', models.CharField(blank=True, max_length=250, null=True)),
                ('key', models.CharField(blank=True, max_length=50, null=True)),
                ('composer', models.CharField(blank=True, max_length=250, null=True)),
                ('lyricist', models.CharField(blank=True, max_length=250, null=True)),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
                ('remixer', models.CharField(blank=True, max_length=250, null=True)),
                ('label', models.CharField(blank=True, max_length=250, null=True)),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
