# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-17 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0002_auto_20160717_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='lyrics',
            field=models.TextField(blank=True, null=True, verbose_name='Lyrics'),
        ),
    ]
